# docker-compose.yml for local development of the Prompt Backend Service

version: '3.8'

services:
  prompt-service:
    # Build the image from the Dockerfile in the current directory
    build: .
    container_name: prompt_backend_local
    # Environment variables for development configuration
    environment:
      - LOG_LEVEL=debug
      # Override the prompt library path if needed for local testing
      - PROMPT_LIB_PATH=/app/prompt_library_local # Path inside container
    ports:
      # Map port 8000 on the host to port 8000 in the container,
      # binding ONLY to localhost on the host machine for security.
      - "127.0.0.1:8000:8000"
    volumes:
      # Mount the local application code into the container for hot reloading
      # Assumes your FastAPI code is in an 'app' directory locally
      - ./app:/app/app
      # Mount the local prompt library into the container
      # Assumes your prompt library is in a 'prompt_library_local' directory locally
      # This allows changes to prompts to be picked up by the service (if it reloads on changes)
      - ./prompt_library_local:/app/prompt_library_local
    # Override the default command to enable --reload for uvicorn
    # This watches for changes in the mounted /app directory and restarts the server
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

# Optional: Define named volumes if needed for persistent data (less likely for this service)
# volumes:
#   prompt_cache:

# Optional: Define networks if needed for inter-service communication
# networks:
#   prompt_net: