# In .github/workflows/codebase-ci.yml (Component #7) or prompts-ci.yml (Component #6)
# ...
    - name: Scan for Secrets (GitGuardian)
      uses: GitGuardian/ggshield-action@v1.20.0
      env:
        # API Key stored as GitHub Secret
        GITGUARDIAN_API_KEY: ${{ secrets.COMPANY_GITGUARDIAN_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For PR comments/status checks
      with:
        # Optional: Specify a custom configuration file path
        # config_path: .gitguardian.yml

        # Optional: Set exit-zero to NOT fail the build on secrets (use for monitoring only - not recommended for enforcement)
        # exit_zero: true

        # Optional: Show secrets in logs (DISABLE for production/security reasons)
        # show_secrets: false

        # Optional: Ignore specific patterns or paths via .gitguardian.yml or secrets allowlist